name: Typescript compiler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Install modules
        run: npm install
      - uses: iCrawl/action-tsc@v1
